# Generated by Django 3.2 on 2022-02-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
